# originated from https://github.com/onk/onkcop/blob/master/config/rubocop.yml
#
# target_version:
#   rubocop v0.52.1

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'vendor/**/*' # rubocop config/default.yml
    - 'db/schema.rb'
    - 'db/fixtures/**/*'
    - 'config/**/*'
    - 'bin/*'
  DisplayCopNames: true
  NewCops: enable

# ##################### Rails ##################################

require:
  - rubocop-rails

Rails:
  Enabled: true

##################### Style ##################################

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  AutoCorrect: false
  Exclude:
    - 'spec/**/*'

Style/CollectionMethods:
  PreferredMethods:
    detect: 'detect'
    find: 'detect'
    inject: 'inject'
    reduce: 'inject'

Style/PreferredHashMethods:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/FormatString:
  EnforcedStyle: percent

Style/GuardClause:
  MinBodyLength: 5

Style/HashSyntax:
  Exclude:
    - '**/*.rake'
    - 'Rakefile'

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 7

Style/PerlBackrefs:
  AutoCorrect: false

Style/RedundantSelf:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/Semicolon:
  Exclude:
    - 'spec/**/*'

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

##################### Lint ##################################

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*.rb'

Metrics/PerceivedComplexity:
  Max: 8

##################### Layout ##################################

Layout/LineLength:
  Max: 100
  Exclude:
    - 'db/migrate/*.rb'

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/ExtraSpacing:
  Exclude:
    - 'db/migrate/*.rb'

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/SpaceAroundOperators:
  AllowForAlignment: true

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

##################### Other ##################################

Naming/FileName:
  Enabled: false
