version: '3.8'
services:
  db:
    image: mariadb:10.5
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mariadb:/var/lib/mysql
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ROOT: $APP_ROOT
    image: ${APP_NAME}
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:${APP_ROOT}
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    tty: true
    stdin_open: true
